### ISSUE TITLE
Legal demand to remove leveldb.org

### ISSUE THREAD

**Issue by heapwolf** [Level/leveljs.org#45]
Google's lawyers have demanded this organization stop using `leveldb` (I'm not sure if it's trademarked?). I removed the `CNAME` file from the gh-pages branch so that it no longer serves the current build. In master I've renamed any references to `leveldb` in the README.md file. Someone motivated might want to get the domain `leveljs.org` since it's available and deploy an updated version of the site that is more specific to the `js` part of this project.

**Comment by mcollina** [comment]
Or maybe one of those fancy .dev domains?

**Comment by ralphtheninja** [comment]
We might need to consider leaving the `level*` naming scheme completely.

**Comment by vweevers** [comment]
See also https://github.com/Level/community/issues/66 (let's answer that first).

**Comment by vweevers** [comment]
I bought `leveljs.org` and started working (in no particular rush, letting things play out) on an updated website:

![image](https://user-images.githubusercontent.com/3055345/56093026-090da180-5ec4-11e9-9c7a-3aa5ece522f9.png)

**Comment by vweevers** [comment]
It's live: https://leveljs.org/
