### ISSUE TITLE
Take care of the security issues

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveljs.org#47]
![Screenshot from 2019-04-15 11-33-38](https://user-images.githubusercontent.com/308049/56122286-5c3e2d80-5f72-11e9-8542-1dbcc13178e7.png)

**Comment by vweevers** [comment]
Not urgent because it's only dev dependencies, the website is just static HTML.

**Comment by ralphtheninja** [comment]
Aye, but it looks ugly ;)
